apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oauth2-proxy-admission-controller.fullname" . }}
  labels:
{{ include "oauth2-proxy-admission-controller.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "oauth2-proxy-admission-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "oauth2-proxy-admission-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
