apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oauth2-proxy-admission-controller.fullname" . }}
  labels:
{{ include "oauth2-proxy-admission-controller.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete", "list", "patch", "update"]