---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy-admission-controller.fullname" . }}
  labels:
    {{- include "oauth2-proxy-admission-controller.labels" . | nindent 4 }}
type: Opaque
data:
  default-secret-name: {{ include "oauth2-proxy-admission-controller.fullname" . | b64enc | quote }}
  default-secret-namespace: {{ .Release.Namespace | b64enc | quote }}
  proxy-container-name: {{ .Values.proxy.containerName | b64enc | quote }}
  proxy-http-port: {{ .Values.proxy.httpPort | b64enc | quote }}
  proxy-email-domains: {{ .Values.proxy.emailDomains | b64enc | quote }}
  {{- if .Values.proxy.allowedGroups }}
  proxy-allowed-groups: {{ .Values.proxy.allowedGroups | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.clientId }}
  proxy-client-id: {{ .Values.proxy.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.clientSecret }}
  proxy-client-secret: {{ .Values.proxy.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.redirectUrl }}
  proxy-redirect-url: {{ .Values.proxy.redirectUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.oidcIssuerUrl }}
  proxy-oidc-issuer-url: {{ .Values.proxy.oidcIssuerUrl | b64enc | quote }}
  {{- end }}
  proxy-cookie-name: {{ .Values.proxy.cookieName | b64enc | quote }}
  {{- if .Values.proxy.cookieDomain }}
  proxy-cookie-domain: {{ .Values.proxy.cookieDomain | b64enc | quote }}
  {{- end }}
  {{- if .Values.proxy.cookieSecret }}
  proxy-cookie-secret: {{ .Values.proxy.cookieSecret | b64enc | quote }}
  {{- end }}
  proxy-resources-requests-cpu: {{ .Values.proxy.requestsCpu | b64enc | quote }}
  proxy-resources-requests-memory: {{ .Values.proxy.requestsMemory | b64enc | quote }}
  proxy-resources-limits-cpu: {{ .Values.proxy.limitsCpu | b64enc | quote }}
  proxy-resources-limits-memory: {{ .Values.proxy.limitsMemory | b64enc | quote }}
  proxy-container-image: {{ .Values.proxy.image | b64enc | quote }}
  proxy-container-tag: {{ .Values.proxy.tag | b64enc | quote }}
  proxy-container-image-pull-policy: {{ .Values.proxy.imagePullPolicy | b64enc | quote }}