---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oauth2-proxy-admission-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  name: {{ template "oauth2-proxy-admission-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.admissionWebhooks.servicePort }}
      protocol: TCP
      targetPort: webhook-server
  selector:
      {{- include "oauth2-proxy-admission-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller-manager
